name: "Worker: Step 1 - Mirror 3rd Party to Local"

on:
  workflow_dispatch:
  push:
    branches:
    - '**'
  schedule:
    - cron: '30 12 * * 1,3,5'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          repository: open-metadata/OpenMetadata
          # path: OpenMetadata
          fetch-depth: 0
          # token: $${{ secrets.GIT_TOKEN }}
      - name: mirror-repository
        # You may pin to the exact commit or the version.
        # uses: yesolutions/mirror-action@082a9611ed4b64c796245a62b34584ee2ded6833
        # uses: yesolutions/mirror-action@v0.6.0
        uses: yesolutions/mirror-action@master
        with:
          # The remote ref name to use. 'mirror' by default. Useful to avoid conflicts with existing remotes.
          REMOTE_NAME: 'OpenMetadata-Mirror'
          # The remote repository e.g. https://github.com/octocat/foo.git or git@github.com:octocat/foo.git
          REMOTE: 'git@github.com:Jason-Clark-FG/OpenMetadata-Mirror.git'
          # Username for remote repository
          #GIT_USERNAME: # optional
          # The git https password or token for the remote repository
          #GIT_PASSWORD: # optional
          # The ssh private key for writing to the remote repository, if using ssh
          GIT_SSH_PRIVATE_KEY: ${{ secrets.GIT_SSH_PRIVATE_KEY }} # optional
          # The ssh public key for writing to the remote repository. Normally, not required at all
          GIT_SSH_PUBLIC_KEY: ${{ secrets.GIT_SSH_PUBLIC_KEY }} # optional
          # The contents of a SSH known_hosts file for host key verification
          # GIT_SSH_KNOWN_HOSTS: ${{ secrets.GIT_SSH_KNOWN_HOSTS }} # optional
          # if true, skips host key verification. Mutually exclusive with GIT_SSH_KNOWN_HOSTS
          GIT_SSH_NO_VERIFY_HOST: "true" # optional, default is false
          # Push all refs instead of just the current branch
          #PUSH_ALL_REFS: # optional, default is true
          # The arugments to use when pushing the repository
          #GIT_PUSH_ARGS: # optional, default is --tags --force --prune
          # set to "true" to enable debug mode
          DEBUG: "true" # optional, default is false
